# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import taskgrid_pb2 as taskgrid__pb2


class ClientServiceStub(object):
    """Client Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTask = channel.unary_unary(
                '/taskgrid.ClientService/SendTask',
                request_serializer=taskgrid__pb2.SendTaskRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.SendTaskResponse.FromString,
                )
        self.RequestResult = channel.unary_unary(
                '/taskgrid.ClientService/RequestResult',
                request_serializer=taskgrid__pb2.RequestResultRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.RequestResultResponse.FromString,
                )


class ClientServiceServicer(object):
    """Client Service
    """

    def SendTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTask,
                    request_deserializer=taskgrid__pb2.SendTaskRequest.FromString,
                    response_serializer=taskgrid__pb2.SendTaskResponse.SerializeToString,
            ),
            'RequestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestResult,
                    request_deserializer=taskgrid__pb2.RequestResultRequest.FromString,
                    response_serializer=taskgrid__pb2.RequestResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Client Service
    """

    @staticmethod
    def SendTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.ClientService/SendTask',
            taskgrid__pb2.SendTaskRequest.SerializeToString,
            taskgrid__pb2.SendTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.ClientService/RequestResult',
            taskgrid__pb2.RequestResultRequest.SerializeToString,
            taskgrid__pb2.RequestResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class WorkerServiceStub(object):
    """Worker Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTask = channel.unary_unary(
                '/taskgrid.WorkerService/ProcessTask',
                request_serializer=taskgrid__pb2.Task.SerializeToString,
                response_deserializer=taskgrid__pb2.ProcessTaskResponse.FromString,
                )


class WorkerServiceServicer(object):
    """Worker Service
    """

    def ProcessTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTask,
                    request_deserializer=taskgrid__pb2.Task.FromString,
                    response_serializer=taskgrid__pb2.ProcessTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker Service
    """

    @staticmethod
    def ProcessTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.WorkerService/ProcessTask',
            taskgrid__pb2.Task.SerializeToString,
            taskgrid__pb2.ProcessTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NameServiceStub(object):
    """Nameservice Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/taskgrid.NameService/RegisterWorker',
                request_serializer=taskgrid__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.RegisterWorkerResponse.FromString,
                )
        self.LookupWorker = channel.unary_unary(
                '/taskgrid.NameService/LookupWorker',
                request_serializer=taskgrid__pb2.LookupWorkerRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.LookupWorkerResponse.FromString,
                )
        self.DeregisterWorker = channel.unary_unary(
                '/taskgrid.NameService/DeregisterWorker',
                request_serializer=taskgrid__pb2.DeregisterWorkerRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.DeregisterWorkerResponse.FromString,
                )


class NameServiceServicer(object):
    """Nameservice Service
    """

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=taskgrid__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=taskgrid__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'LookupWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupWorker,
                    request_deserializer=taskgrid__pb2.LookupWorkerRequest.FromString,
                    response_serializer=taskgrid__pb2.LookupWorkerResponse.SerializeToString,
            ),
            'DeregisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterWorker,
                    request_deserializer=taskgrid__pb2.DeregisterWorkerRequest.FromString,
                    response_serializer=taskgrid__pb2.DeregisterWorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.NameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NameService(object):
    """Nameservice Service
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.NameService/RegisterWorker',
            taskgrid__pb2.RegisterWorkerRequest.SerializeToString,
            taskgrid__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LookupWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.NameService/LookupWorker',
            taskgrid__pb2.LookupWorkerRequest.SerializeToString,
            taskgrid__pb2.LookupWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeregisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.NameService/DeregisterWorker',
            taskgrid__pb2.DeregisterWorkerRequest.SerializeToString,
            taskgrid__pb2.DeregisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MonitoringServiceStub(object):
    """Monitoring Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStats = channel.unary_unary(
                '/taskgrid.MonitoringService/GetSystemStats',
                request_serializer=taskgrid__pb2.SystemStatsRequest.SerializeToString,
                response_deserializer=taskgrid__pb2.SystemStatsResponse.FromString,
                )


class MonitoringServiceServicer(object):
    """Monitoring Service
    """

    def GetSystemStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=taskgrid__pb2.SystemStatsRequest.FromString,
                    response_serializer=taskgrid__pb2.SystemStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskgrid.MonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Monitoring Service
    """

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/taskgrid.MonitoringService/GetSystemStats',
            taskgrid__pb2.SystemStatsRequest.SerializeToString,
            taskgrid__pb2.SystemStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
